### ISSUE TITLE
ability target positions

### ISSUE THREAD

**Issue by jblanchette** [anXieTyPB/w3gjs#15]
great tool, thanks for releasing it :+1: 

have a question about when looking at the `targetX` and `targetY` values of an ActionBlock with those properties - it seems the values are large numbers

`x: -980223926, y: 1162084274`

is there additional conversion needed to align them to the map coordinates?  for example Echo Isles seems to be only ~10,000 units wide in the world editor

thanks!

**Comment by anXieTyPB** [comment]
Currently numbers are (incorrectly) parsed as int32 everywhere. The w3g specification explains that click coordinates are saved as 32bit IEEE floating point numbers. 

Therefore the parser has to be adjusted to read floating point values instead of int.

Take a look at the following line:
https://github.com/anXieTyPB/w3gjs/blob/393f9b2cfe7df9562a4c888b42eacc92c5ef4170/parsers/actions.js#L33

Changing the int32le to floatle should work to get the proper coordinates.
Maximum range is -16384.000 to 16384.000 (256x256 maps).

**Comment by anXieTyPB** [comment]
I set up a branch with the changes required:
https://github.com/anXieTyPB/w3gjs/pull/16

Check it out and see if it fits your needs.

**Comment by JFGHT** [comment]
Now that you're talking about coords, would it be possible to detect players's starting positions?

**Comment by jblanchette** [comment]
the branch fixes work great :+1:   thanks for the explanation on the fix.

I am also highly interested in starting locations - I was wondering if that was encoded in the 'random seed' potentially?

**Comment by anXieTyPB** [comment]
I merged the branch into master. Please open another issue about determining the player start positions.
