### ISSUE TITLE
Determining player starting map position

### ISSUE THREAD

**Issue by jblanchette** [anXieTyPB/w3gjs#17]
Per request a new issue.

Wondering if it's possible to determine player starting position from the replay for a given map?

I haven't found any related documentation on the topic from other replay format docs.  My current guess would be that the information is potentially in the given 'random seed' for the map?

**Comment by anXieTyPB** [comment]
The random seed is used to initialize the random number generator across all clients so that everyone can run the same deterministic simulation (if you want more information look up deterministic lockstep in rts games). 

As a consequence, the random number generator also determines the player starting positions. What you can do is infer the starting position from the first N actions of a player. Another possible scenario is generating a heatmap that shows game activity over time on the map.

**Comment by jblanchette** [comment]
Ah darn, it seemed very likely it would come from the seed :)

I'll continue onward using estimation / prediction like suggested - closing this off, thanks!
