### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by JFGHT** [anXieTyPB/w3gjs#4]
First of all, thanks for your time spent in this newly made parser; it indeed looks more modular than others.

In a few days I'll be having more spare time to play with stuff like this and I probably help you by creating some PR. But first I'd like to ask you a few questions:

- Are you parsing any new data compared to the classic parser made by julas? (Here the nodejs version: https://github.com/HydraOrc/w3g).

- Did you manage to find the correct offsets for the winner? There were some weird behaviours detecting the correct winner in custom games.

- Why didn't you use es6 classes? they're cleaner and newer, and since you made it from scratch...

Thank you.

PS: this is crearly not an issue, I just had no other way to get in touch with you.

**Comment by JFGHT** [comment]
Okay, nice!

Is there a way we can get in touch more directly?

Regards.

**Comment by anXieTyPB** [comment]
I prefer to do most of discussions in the issues section so that anyone can read up on it if interested and everyone has the same chance to aquire information about the project. I am going to open a discussion ticket for a feature roadmap this weekend.

Besides of that, I am lurking around the B2W Discord, just in case you use it you can contact me there aswell.
